#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
logging:
  config: classpath:log4j2.yml
  level:
    ROOT: INFO
    org.ylzl: DEBUG
    ${package}: INFO
    ${package}.dao.mybatis.mapper: DEBUG

server:
  port: 9090

spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://127.0.0.1:3306/test?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 5000
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  thymeleaf:
    cache: false
