#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
application:
  qcloud:
    ak: AKIDiCQRlCjHyShkX4TO9dJsGOGNGtFNFG0t
    sk: XprdAxUlmW1HGVUCfPsCG4aqrMcKoAH8
    cos:
      region: ap-shanghai
      topic-id: # TODO
      bucket-name: ${symbol_dollar}{spring.application.name}-log

logging:
  config: classpath:logback-spring-cls.xml
  level:
    ROOT: WARN
    org.ylzl: INFO
    ${package}: INFO
    ${package}.dao.mybatis: DEBUG

rocketmq:
  name-server: 127.0.0.1:9876;127.0.0.1:9876
  producer:
    group: PROD
    send-message-timeout: 5000

server:
  compression:
    enabled: false
    mime-types: text/html,text/plain,text/css,application/javascript
    min-response-size: 1024
  port: 9090

spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://127.0.0.1:3306/test?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 5000
      validation-query: select 1
      validation-query-timeout: 3
      test-on-return: false
      test-while-idle: true
      test-on-borrow: true
      stat-view-servlet:
        enabled: true
      filter:
        stat:
          enabled: true
          db-type: mysql
          slow-sql-millis: 5000
          log-slow-sql: true
      web-stat-filter:
        enabled: true
        login-username: admin
        login-password: admin
      min-evictable-idle-time-millis: 600000
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      username:
      password:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
  thymeleaf:
    cache: true
