openapi: 3.0.1
info:
  title: API 接口
  description: API 描述
  version: 1.0.0-SNAPSHOT
  contact:
    name: ${author}
    email: ${email}
servers:
  - url: '/v1'
paths:
  # 获取站点列表接口
  /sites:
    get:
      operationId: getSites
      tags:
        - Site 站点
      summary: 获取站点列表
      responses:
        '200':
          description: 返回数据
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SiteVM'
        '400':
          description: 客户端错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVM'
        '401':
          description: 客户端未认证
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVM'
        '403':
          description: 客户端非法访问
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVM'
        '500':
          description: 服务端错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVM'
      security:
        - http: [ ]

components:
  securitySchemes:
    http:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # 异常返回信息视图模型
    ErrorVM:
      type: object
      properties:
        message:
          type: string
          description: 展示消息
        description:
          type: string
          description: 具体错误

    # 站点视图模型
    SiteVM:
      type: object
      properties:
        id:
          type: integer
          description: 站点 ID
        siteName:
          type: string
          description: 站点名字
        siteNameEn:
          type: string
          description: 站点名字(英文)
        currency:
          type: string
          description: 货币符号
        domains:
          type: string
          description: 域名
